### CREATE EVENT
POST http://localhost:3000/events HTTP/1.1
content-type: application/json

{
    "userID": "1",
    "attendees": ["1", "2"],
    "startEvent": "2024-11-14T15:30:00",
    "endEvent": "2024-11-14T16:30:00",
    "title": "John Doe Appointment"
}

### CREATE EVENT
POST http://localhost:3000/events HTTP/1.1
content-type: application/json

{
    "userID": "3",
    "attendees": ["2", "3"],
    "startEvent": "2024-12-14T15:30:00",
    "endEvent": "2024-12-14T16:30:00",
    "title": "Jane Doe Appointment"
}

### CREATE EVENT
POST http://localhost:3000/events HTTP/1.1
content-type: application/json

{
    "userID": "4",
    "attendees": ["2", "4"],
    "startEvent": "2024-12-14T15:30:00",
    "endEvent": "2024-12-14T16:30:00",
    "title": "Moe Lake Surgery"
}

### GET EVENT
GET http://localhost:3000/1/dates?start=2024-11-14T15:30:00&end=2024-11-14T16:30:00

### DELETE EVENT
DELETE http://localhost:3000/6731796709c436e6a3bb447b
